apiVersion: v1
kind: Pod
metadata:
  name: k8s-debug-pod
  labels:
    purpose: debug
spec:
  containers:
  - name: k8s-debug
    image: tang2432/k8s:latest
    resources:
      limits:
        memory: "8Gi"
        cpu: "4"
      requests:
        memory: "4Gi"
        cpu: "2"
