apiVersion: v1
kind: Pod
metadata:
  name: k8s-debug-pod
  labels:
    purpose: debug
spec:
  containers:
  - name: k8s-debug
    image: nicolaka/netshoot:latest
    command:
      - /bin/bash
      - -c
      - while true; do sleep 3600; done