apiVersion: apps/v1
kind: Deployment
metadata:
  name: tang-debug-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tang-debug
  template:
    metadata:
      labels:
        app: tang-debug
    spec:
      containers:
      - name: tang-debug
        image: tang2432/k8s:latest
        resources:
          limits:
            memory: "8Gi"
            cpu: "4"
          requests:
            memory: "4Gi"
            cpu: "2"
