text = """

albumentations                               1.3.1
alembic                                      1.12.0
altair                                       5.1.1
anaconda-client                              1.11.2
anaconda-navigator                           2.4.0
anaconda-project                             0.11.1
annotated-types                              0.5.0
anthropic                                    0.3.11
antlr4-python3-runtime                       4.9.3
anyio                                        3.5.0
appdirs                                      1.4.4
applaunchservices                            0.3.0
appnope                                      0.1.2
appscript                                    1.1.2
APScheduler                                  3.10.1
argon2-cffi                                  21.3.0
argon2-cffi-bindings                         21.2.0
array-record                                 0.4.1
arrow                                        1.2.3
asgiref                                      3.7.2
astroid                                      2.14.2
astropy                                      5.1
asttokens                                    2.0.5
astunparse                                   1.6.3
async-lru                                    2.0.4
async-timeout                                4.0.2
atomicwrites                                 1.4.0
attrs                                        23.1.0
Authlib                                      1.2.1
Automat                                      20.2.0
av                                           10.0.0
awscli                                       1.29.52
Babel                                        2.11.0
backcall                                     0.2.0
backoff                                      2.2.1
backports.functools-lru-cache                1.6.4
backports.tempfile                           1.0
backports.weakref                            1.0.post1
banal                                        1.0.6
basicsr                                      1.4.2
bcrypt                                       3.2.0
beautifulsoup4                               4.12.2
binaryornot                                  0.4.4
black                                        22.6.0
bleach                                       4.1.0
blendmodes                                   2022
blind-watermark                              0.4.4
blinker                                      1.6.2
bokeh                                        2.4.3
boltons                                      23.0.0
boto3                                        1.28.17
botocore                                     1.31.52
Bottleneck                                   1.3.5
braceexpand                                  0.1.7
Brotli                                       1.0.9
brotlipy                                     0.7.0
build                                        0.10.0
cachetools                                   5.3.1
certifi                                      2023.7.22
cffi                                         1.15.1
chardet                                      4.0.0
charset-normalizer                           2.0.4
chromadb                                     0.3.26
clean-fid                                    0.1.35
click                                        8.1.7
click-log                                    0.4.0
clickhouse-connect                           0.6.11
clip                                         1.0
cloudpickle                                  2.2.1
clyent                                       1.2.2
cohere                                       4.22
colorama                                     0.4.4
colorcet                                     3.0.1
coloredlogs                                  15.0.1
comm                                         0.1.2
conda                                        23.3.1
conda-build                                  3.24.0
conda-content-trust                          0.1.3
conda-pack                                   0.6.0
conda-package-handling                       2.0.2
conda_package_streaming                      0.7.0
conda-repo-cli                               1.0.41
conda-token                                  0.4.0
conda-verify                                 3.4.2
constantly                                   15.1.0
contextlib2                                  21.6.0
contourpy                                    1.0.5
controlnet-aux                               0.0.6
cookiecutter                                 1.7.3
crayons                                      0.4.0
cryptography                                 41.0.3
cssselect                                    1.1.0
cycler                                       0.11.0
Cython                                       0.29.36
cytoolz                                      0.12.0
dask                                         2022.7.0
databricks-cli                               0.17.7
dataclasses-json                             0.5.14
dataset                                      1.6.2
datasets                                     2.14.2
datashader                                   0.14.4
datashape                                    0.5.4
debugpy                                      1.5.1
decorator                                    5.1.1
defusedxml                                   0.7.1
Deprecated                                   1.2.14
deprecation                                  2.1.0
diff-match-patch                             20200713
diffusers                                    0.19.3
dill                                         0.3.7
distlib                                      0.3.7
distributed                                  2022.7.0
distro                                       1.8.0
Django                                       4.2.4
dm-tree                                      0.1.8
dnspython                                    2.4.2
docarray                                     0.21.1
docker                                       6.1.3
docker-pycreds                               0.4.0
docstring-parser                             0.15
docstring-to-markdown                        0.11
docutils                                     0.16
dotty-dict                                   1.3.1
duckdb                                       0.8.1
easydict                                     1.10
ecdsa                                        0.18.0
einops                                       0.4.1
emoji                                        2.8.0
entrypoints                                  0.4
et-xmlfile                                   1.1.0
etils                                        1.4.1
executing                                    0.8.3
executor                                     23.2
face-alignment                               1.4.0
facexlib                                     0.3.0
faiss-cpu                                    1.7.4
fake-useragent                               1.2.1
fastapi                                      0.100.1
fastapi_amis_admin                           0.6.0
fastapi_scheduler                            0.0.13
fastavro                                     1.8.2
fasteners                                    0.19
fastjsonschema                               2.16.2
ffmpy                                        0.3.0
filelock                                     3.12.2
filetype                                     1.2.0
filterpy                                     1.4.5
flake8                                       6.0.0
Flask                                        2.3.3
flatbuffers                                  23.5.26
flit_core                                    3.6.0
fonttools                                    4.25.0
fqdn                                         1.5.1
frozenlist                                   1.3.3
fsspec                                       2022.11.0
ftfy                                         6.1.1
future                                       0.18.3
gast                                         0.4.0
gdown                                        4.7.1
gensim                                       4.3.0
gevent                                       23.7.0
geventhttpclient                             2.0.10
gfpgan                                       1.3.5
gitdb                                        4.0.10
GitPython                                    3.1.32
glob2                                        0.7
gmpy2                                        2.1.2
google-api-core                              2.11.1
google-api-python-client                     2.97.0
google-auth                                  2.20.0
google-auth-httplib2                         0.1.0
google-auth-oauthlib                         1.0.0
google-cloud-aiplatform                      1.31.1
google-cloud-bigquery                        3.11.4
google-cloud-core                            2.3.3
google-cloud-resource-manager                1.10.3
google-cloud-storage                         2.10.0
google-crc32c                                1.5.0
google-pasta                                 0.2.0
google-resumable-media                       2.5.0
google-search-results                        2.4.1
googleapis-common-protos                     1.60.0
gotrue                                       1.0.4
gradio                                       3.35.2
gradio_client                                0.2.7
greenlet                                     2.0.1
grpc-google-iam-v1                           0.12.6
grpcio                                       1.58.0
grpcio-health-checking                       1.47.5
grpcio-reflection                            1.47.5
grpcio-status                                1.47.5
grpcio-tools                                 1.58.0
gunicorn                                     21.2.0
h11                                          0.12.0
h2                                           4.1.0
h5py                                         3.7.0
HeapDict                                     1.0.1
hnswlib                                      0.7.0
holoviews                                    1.15.4
hpack                                        4.0.0
httpcore                                     0.15.0
httplib2                                     0.22.0
httptools                                    0.6.0
httpx                                        0.23.3
huggingface-hub                              0.16.4
humanfriendly                                10.0
hvplot                                       0.8.2
hyperframe                                   6.0.1
hyperlink                                    21.0.0
idna                                         3.4
imagecodecs                                  2021.8.26
imageio                                      2.26.0
imagesize                                    1.4.1
imbalanced-learn                             0.10.1
importlib-metadata                           6.8.0
importlib-resources                          6.0.1
incremental                                  21.3.0
inflection                                   0.5.1
iniconfig                                    1.1.1
insightface                                  0.7.3
install                                      1.3.5
intake                                       0.6.7
intervaltree                                 3.1.0
invoke                                       1.7.3
ipykernel                                    6.19.2
ipython                                      8.10.0
ipython-genutils                             0.2.0
isoduration                                  20.11.0
isort                                        5.9.3
itemadapter                                  0.3.0
itemloaders                                  1.0.4
itsdangerous                                 2.1.2
jaraco.classes                               3.3.0
jcloud                                       0.2.16
jedi                                         0.18.1
jellyfish                                    0.9.0
jina-hubble-sdk                              0.39.0
Jinja2                                       3.1.2
jinja2-time                                  0.2.0
jmespath                                     0.10.0
joblib                                       1.1.1
json5                                        0.9.6
jsonmerge                                    1.8.0
jsonpatch                                    1.32
jsonpointer                                  2.1
jsonschema                                   4.18.4
jsonschema-specifications                    2023.7.1
jupyter_client                               8.3.0
jupyter_core                                 5.2.0
jupyter-events                               0.7.0
jupyter-lsp                                  2.2.0
jupyter_server                               2.7.0
jupyter_server_terminals                     0.4.4
jupyterlab                                   4.0.3
jupyterlab-pygments                          0.1.2
jupyterlab_server                            2.24.0
keras                                        2.13.1
keras-core                                   0.1.4
keras-cv                                     0.6.1
keyring                                      24.2.0
kiwisolver                                   1.4.4
kornia                                       0.6.12
langchain                                    0.0.256
langchain-experimental                       0.0.8
langsmith                                    0.0.33
lark                                         1.1.7
lazy_loader                                  0.2
lazy-object-proxy                            1.6.0
libarchive-c                                 2.9
libclang                                     16.0.0
lightning-bolts                              0.7.0
lightning-utilities                          0.8.0
linkify-it-py                                2.0.2
llvmlite                                     0.39.1
lmdb                                         1.4.1
locket                                       1.0.0
loguru                                       0.7.1
lpips                                        0.1.4
lxml                                         4.9.3
lz4                                          3.1.3
Mako                                         1.2.4
Markdown                                     3.4.1
markdown-it-py                               2.2.0
MarkupSafe                                   2.1.1
marshmallow                                  3.20.1
matplotlib                                   3.7.0
matplotlib-inline                            0.1.6
mccabe                                       0.7.0
mdit-py-plugins                              0.3.3
mdurl                                        0.1.2
mediapipe                                    0.10.1
metal_sdk                                    2.0.6
metaphor-python                              0.1.16
mistune                                      0.8.4
mlflow                                       2.6.0
mmagic                                       1.0.1
mmcv                                         2.0.1
mmengine                                     0.7.4
mock                                         4.0.3
model-index                                  0.1.11
monotonic                                    1.6
more-itertools                               10.1.0
mpmath                                       1.2.1
msgpack                                      1.0.3
multidict                                    6.0.4
multipledispatch                             0.6.0
multiprocess                                 0.70.15
munkres                                      1.1.4
mypy-extensions                              0.4.3
namex                                        0.0.7
natsort                                      8.4.0
navigator-updater                            0.3.0
nbclassic                                    0.5.2
nbclient                                     0.5.13
nbconvert                                    6.5.4
nbformat                                     5.7.0
nest-asyncio                                 1.5.6
networkx                                     3.1
nltk                                         3.7
notebook                                     7.0.1
notebook_shim                                0.2.2
numba                                        0.56.4
numexpr                                      2.8.4
numpy                                        1.23.5
numpydoc                                     1.5.0
oauthlib                                     3.2.2
omegaconf                                    2.2.3
onnx                                         1.12.0
onnx-tool                                    0.6.4
onnxruntime                                  1.15.1
openai                                       0.27.8
openapi-schema-pydantic                      1.2.4
opencv-contrib-python                        4.8.0.74
opencv-python                                4.7.0.72
opencv-python-headless                       4.8.0.74
opendatalab                                  0.0.9
openmim                                      0.3.9
openpyxl                                     3.0.10
opentelemetry-api                            1.19.0
opentelemetry-exporter-otlp                  1.19.0
opentelemetry-exporter-otlp-proto-common     1.19.0
opentelemetry-exporter-otlp-proto-grpc       1.19.0
opentelemetry-exporter-otlp-proto-http       1.19.0
opentelemetry-exporter-prometheus            1.12.0rc1
opentelemetry-instrumentation                0.40b0
opentelemetry-instrumentation-aiohttp-client 0.40b0
opentelemetry-instrumentation-asgi           0.40b0
opentelemetry-instrumentation-fastapi        0.40b0
opentelemetry-instrumentation-grpc           0.40b0
opentelemetry-proto                          1.19.0
opentelemetry-sdk                            1.19.0
opentelemetry-semantic-conventions           0.40b0
opentelemetry-util-http                      0.40b0
opt-einsum                                   3.3.0
ordered-set                                  4.1.0
orjson                                       3.9.3
overrides                                    7.3.1
packaging                                    22.0
pandas                                       1.5.3
pandocfilters                                1.5.0
panel                                        0.14.3
param                                        1.12.3
parsel                                       1.6.0
parso                                        0.8.3
partd                                        1.2.0
pathlib                                      1.0.1
pathos                                       0.3.1
pathspec                                     0.10.3
pathtools                                    0.1.2
patsy                                        0.5.3
pep8                                         1.7.1
pexpect                                      4.8.0
pickleshare                                  0.7.5
piexif                                       1.1.3
Pillow                                       9.5.0
pinecone-client                              2.2.2
pip                                          22.3.1
pkginfo                                      1.9.6
platformdirs                                 3.10.0
plotly                                       5.9.0
pluggy                                       1.0.0
ply                                          3.11
pooch                                        1.4.0
portalocker                                  2.7.0
postgrest                                    0.10.6
posthog                                      3.0.2
pox                                          0.3.3
poyo                                         0.5.0
ppft                                         1.7.6.7
prettytable                                  3.8.0
prometheus-client                            0.14.1
promise                                      2.3
prompt-toolkit                               3.0.36
promptflow                                   0.1.0b6
promptflow-tools                             0.1.0b6
property-manager                             3.0
Protego                                      0.1.16
proto-plus                                   1.22.3
protobuf                                     4.24.3
psutil                                       5.9.0
psycopg                                      3.1.10
psycopg-binary                               3.1.10
psycopg2-binary                              2.9.7
ptyprocess                                   0.7.0
pulsar-client                                3.3.0
pure-eval                                    0.2.2
py                                           1.11.0
pyarrow                                      12.0.1
pyasn1                                       0.4.8
pyasn1-modules                               0.2.8
pycodestyle                                  2.10.0
pycosat                                      0.6.4
pycparser                                    2.21
pycryptodome                                 3.18.0
pyct                                         0.5.0
pycurl                                       7.45.1
pydantic                                     1.10.12
pydantic_core                                2.4.0
pydash                                       5.1.2
pydeck                                       0.8.1b0
PyDispatcher                                 2.0.5
pydocstyle                                   6.3.0
pydub                                        0.25.1
pyerfa                                       2.0.0
pyflakes                                     3.0.1
Pygments                                     2.15.1
PyHamcrest                                   2.0.2
PyJWT                                        2.4.0
pylint                                       2.16.2
pylint-venv                                  2.3.0
pyls-spyder                                  0.4.0
pymongo                                      4.5.0
pyobjc-core                                  9.0
pyobjc-framework-Cocoa                       9.0
pyobjc-framework-CoreServices                9.0
pyobjc-framework-FSEvents                    9.0
pyodbc                                       4.0.34
pyOpenSSL                                    23.0.0
pyparsing                                    3.0.9
pypdf                                        3.15.5
pypng                                        0.20220715.0
pyproject_hooks                              1.0.0
PyQt5-sip                                    12.11.0
pyrsistent                                   0.18.0
PySocks                                      1.7.1
pysrt                                        1.1.2
pytest                                       7.1.2
python-dateutil                              2.8.2
python-dotenv                                1.0.0
python-gitlab                                3.15.0
python-jose                                  3.3.0
python-json-logger                           2.0.7
python-lsp-black                             1.2.1
python-lsp-jsonrpc                           1.0.0
python-lsp-server                            1.7.1
python-magic                                 0.4.27
python-multipart                             0.0.6
python-rapidjson                             1.10
python-semantic-release                      7.33.2
python-slugify                               5.0.2
python-snappy                                0.6.1
pytoolconfig                                 1.2.5
pytorch-lightning                            1.9.5
pytz                                         2022.7
pyviz-comms                                  2.0.2
PyWavelets                                   1.4.1
PyYAML                                       6.0
pyzmq                                        25.1.0
QDarkStyle                                   3.0.2
qdrant-client                                1.4.0
qrcode                                       7.4.2
qstylizer                                    0.2.2
QtAwesome                                    1.2.2
qtconsole                                    5.4.0
QtPy                                         2.2.0
qudida                                       0.0.4
querystring-parser                           1.2.4
queuelib                                     1.5.0
readme-renderer                              40.0
realtime                                     1.0.0
referencing                                  0.30.0
regex                                        2022.7.9
requests                                     2.28.1
requests-file                                1.5.1
requests-oauthlib                            1.3.1
requests-toolbelt                            1.0.0
resize-right                                 0.0.2
rfc3339-validator                            0.1.4
rfc3986                                      1.5.0
rfc3986-validator                            0.1.1
rich                                         13.5.2
rope                                         1.7.0
rpds-py                                      0.9.2
rsa                                          4.7.2
Rtree                                        1.0.1
ruamel.yaml                                  0.17.21
ruamel.yaml.clib                             0.2.6
ruamel-yaml-conda                            0.17.21
s3transfer                                   0.6.2
safetensors                                  0.3.1
sagebox                                      0.0.4
sagemaker                                    2.175.0
schema                                       0.7.5
scikit-image                                 0.19.3
scikit-learn                                 1.2.1
scipy                                        1.10.0
Scrapy                                       2.8.0
sd-webui                                     0.0.1
seaborn                                      0.12.2
semantic-version                             2.10.0
semver                                       2.13.0
Send2Trash                                   1.8.0
sentence-transformers                        2.2.2
sentencepiece                                0.1.99
sentry-sdk                                   1.29.0
service-identity                             18.1.0
setproctitle                                 1.3.2
setuptools                                   65.6.3
Shapely                                      1.8.5.post1
sip                                          6.6.2
six                                          1.16.0
smart-open                                   5.2.1
smdebug-rulesconfig                          1.0.1
smmap                                        5.0.0
sniffio                                      1.2.0
snowballstemmer                              2.2.0
sortedcontainers                             2.4.0
sounddevice                                  0.4.6
soupsieve                                    2.3.2.post1
Sphinx                                       5.0.2
sphinxcontrib-applehelp                      1.0.2
sphinxcontrib-devhelp                        1.0.2
sphinxcontrib-htmlhelp                       2.0.0
sphinxcontrib-jsmath                         1.0.1
sphinxcontrib-qthelp                         1.0.3
sphinxcontrib-serializinghtml                1.1.5
spyder                                       5.4.1
spyder-kernels                               2.4.1
SQLAlchemy                                   1.4.49
sqlalchemy_database                          0.1.0
sqlalchemy2-stubs                            0.0.2a35
sqlmodel                                     0.0.8
sqlparse                                     0.4.4
stack-data                                   0.2.0
starlette                                    0.27.0
statsmodels                                  0.13.5
stegano                                      0.11.2
storage3                                     0.5.3
streamlit                                    1.27.0
StrEnum                                      0.4.15
supabase                                     1.0.3
supafunc                                     0.2.2
sympy                                        1.11.1
tables                                       3.7.0
tabulate                                     0.9.0
tb-nightly                                   2.14.0a20230625
TBB                                          0.2
tblib                                        1.7.0
tenacity                                     8.2.3
tensorboard                                  2.13.0
tensorboard-data-server                      0.7.1
tensorflow                                   2.13.0
tensorflow-datasets                          4.9.2
tensorflow-estimator                         2.13.0
tensorflow-macos                             2.13.0
tensorflow-metadata                          1.14.0
termcolor                                    2.3.0
terminado                                    0.17.1
text-unidecode                               1.3
textdistance                                 4.2.1
threadpoolctl                                2.2.0
three-merge                                  0.1.1
tifffile                                     2021.7.2
tiktoken                                     0.4.0
timm                                         0.9.2
tinycss2                                     1.2.1
tldextract                                   3.2.0
tokenizers                                   0.13.3
tomesd                                       0.1.3
toml                                         0.10.2
tomli                                        2.0.1
tomlkit                                      0.11.1
toolz                                        0.12.0
torch                                        2.0.1
torchaudio                                   2.0.2
torchdata                                    0.6.1
torchdiffeq                                  0.2.3
torchmetrics                                 1.0.1
torchsde                                     0.2.5
torchvision                                  0.15.2
tornado                                      6.3.2
tqdm                                         4.66.1
traitlets                                    5.7.1
trampoline                                   0.1.2
transformers                                 4.30.2
tritonclient                                 2.36.0
twine                                        3.8.0
Twisted                                      22.2.0
typer                                        0.9.0
types-cachetools                             5.3.0.6
typing_extensions                            4.5.0
typing-inspect                               0.9.0
tzdata                                       2023.3
tzlocal                                      5.0.1
uc-micro-py                                  1.0.2
ujson                                        5.4.0
Unidecode                                    1.2.0
unstructured                                 0.10.12
uri-template                                 1.3.0
uritemplate                                  4.1.1
urllib3                                      1.26.14
uvicorn                                      0.22.0
uvloop                                       0.17.0
validators                                   0.21.0
verboselogs                                  1.7
virtualenv                                   20.24.3
w3lib                                        1.21.0
wandb                                        0.15.7
watchdog                                     2.1.6
watchfiles                                   0.20.0
wcwidth                                      0.2.5
weaviate-client                              3.23.2
webcolors                                    1.13
webdataset                                   0.2.48
webencodings                                 0.5.1
websocket-client                             0.58.0
websockets                                   10.4
Werkzeug                                     2.3.7
whatthepatch                                 1.0.2
wheel                                        0.38.4
wikipedia                                    1.4.0
wrapt                                        1.14.1
wurlitzer                                    3.0.2
xarray                                       2022.11.0
xgboost                                      1.7.6
xlwings                                      0.29.1
xxhash                                       3.3.0
yapf                                         0.31.0
yarl                                         1.9.2
zict                                         2.1.0
zipp                                         3.11.0
zope.event                                   5.0
zope.interface                               5.4.0
zstandard                                    0.19.0
"""

# 将文本分割成行
lines = text.splitlines()

# 从第三行开始提取包的名称
package_names = [line.split()[0] for line in lines[2:]]

print(package_names)
